name: "Development environment CI/CD"

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      environment: dev
    secrets:
      aws_assume_role_arn: ${{ secrets.AWS_GITHUB_ACCESS_ROLE_ARN }}
      aws_s3_terraform_backend: ${{ secrets.AWS_TERRAFORM_BACKEND_BUCKET_NAME }}
      aws_region: ${{ secrets.AWS_REGION }}
      docker_access_token: ${{ secrets.DOCKER_ACCESS_TOKEN }}